# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hyde Park Picture House
email: john@jdp.org.uk
description: |
  The cosiest cinema in Leeds
baseurl: "/preview" # the subpath of your site, e.g. /blog
url: "http://www.hydeparkpicturehouse.co.uk" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: hydeparkph
facebook_username: TheHydeParkPictureHouse
instagram_username: hydeparkph

cloudinary: letsdance

header_pages:
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
collections:
  films:
    output: true
    permalink: /:title/index.html
social:
  - name: twitter
    url: https://twitter.com/hydeparkph

defaults:
  - scope:
      path: ""
    values:
      image:
        path: /assets/images/opengraph.jpg
        height: 1200
        width: 1200

breakpoints:
  - 320
  - 480
  - 640
  - 960
  - 1280
  - 1600
  - 2000